spring.application.name=user-service
server.port=8082

# Keycloak configuration
keycloak.auth-server-url=${KEYCLOAK_AUTH_SERVER_URL:http://localhost:8181}
keycloak.realm=${KEYCLOAK_REALM:meta}
keycloak.resource=${KEYCLOAK_RESOURCE:user-service}
keycloak.admin.username=${KEYCLOAK_ADMIN_USERNAME:admin}
keycloak.admin.password=${KEYCLOAK_ADMIN_PASSWORD:admin}
spring.profiles.active=${SPRING_PROFILES_ACTIVE:default}
spring.flyway.enabled=false
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoints.web.base-path=/actuator

# Security configuration
spring.security.oauth2.resourceserver.jwt.issuer-uri=${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI:http://localhost:8181/realms/meta}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI:http://localhost:8181/realms/meta/protocol/openid-connect/certs}

# Swagger Configuration
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
